version: '3.4'

services:
  postgres_todo:
    restart: always
    image: postgres:15.3-alpine
    container_name: database_remandarine
    environment:
      POSTGRES_USER: 12345
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: remandarine
    ports:
      - "7432:5432"

volumes:
  postgres-data-todo: