version: '3.4'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50001:50000"
    user: root
    volumes:
      - //c/Users/Katya/Downloads/jenkins_for:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock