version: '3.4'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    #    volumes:
    #      - .:/RPI_Bot
    #      - ./migrations:/RPI_Bot/migrations
    working_dir: /app
    command: >
      sh -c "python bot.py"
    environment:
      - TZ=Europe/Moscow
      - DB_URL=postgresql://12345:12345@postgres_todo/remandarine
    depends_on:
      - postgres_todo

  postgres_todo:
    restart: always
    image: postgres:15.3-alpine
    container_name: database_remandarine
    environment:
      POSTGRES_USER: 12345
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: remandarine
    ports:
      - "7432:5432"
    volumes:
      - postgres-data-todo:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  postgres-data-todo:
  jenkins_home:
