version: '3.4'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    working_dir: /app
    command: >
      sh -c "python bot.py"
    environment:
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
      - TZ=Europe/Moscow
      - DB_URL=postgresql://12345:12345@postgres_todo/remandarine
    depends_on:
      - postgres_todo

  postgres_todo:
    restart: always
    image: postgres:15.3-alpine
    container_name: database_remandarine
    environment:
      POSTGRES_USER: 12345
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: remandarine
    ports:
      - "7432:5432"
    volumes:
      - postgres-data-todo:/var/lib/postgresql/data

volumes:
  postgres-data-todo: