version: '3.4'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    working_dir: /app
    command: >
      sh -c "/wait-for-it.sh postgres_todo:5432 -- python bot.py"  # Добавляем ожидание базы данных перед запуском приложения
    environment:
      - TZ=Europe/Moscow
      - DB_URL=postgresql://12345:12345@postgres_todo/remandarine
    depends_on:
      - postgres_todo
    volumes:
      - postgres-data-todo:/var/lib/postgresql/data

  postgres_todo:
    restart: always
    image: postgres:15.3-alpine
    container_name: database_remandarine
    environment:
      POSTGRES_USER: 12345
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: remandarine
    ports:
      - "7432:5432"

volumes:
  postgres-data-todo: