version: '3.4'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    working_dir: /app
    command: >
      sh -c "python bot.py"
    environment:
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
      - TZ=Europe/Moscow
      - DB_URL=postgresql://12345:12345@postgres_todo/remandarine
    depends_on:
      - postgres_todo
    volumes:
      - logs:/app/logs

  postgres_todo:
    restart: always
    image: postgres:15.3-alpine
    container_name: database_remandarine
    environment:
      POSTGRES_USER: 12345
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: remandarine
    ports:
      - "7432:5432"
    volumes:
      - postgres-data-todo:/var/lib/postgresql/data

  loki:
    image: grafana/loki:2.7.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.7.1
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
      - logs:/app/logs
    command: -config.file=/etc/promtail/promtail.yaml

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres-data-todo:
  logs: